import type { Metadata } from "next";  // Importing the type Metadata from Next.js for typing the metadata object
import { Geist, Geist_Mono } from "next/font/google";  // Importing font utilities from Google Fonts via Next.js
import "./globals.css";  // Importing global CSS styles

// These are the functions to apply common fonts for the Body

// The Geist font configuration for a sans-serif font. It uses Google Fonts to apply the Geist font style.
const geistSans = Geist({
  variable: "--font-geist-sans",  // A custom CSS variable for the Geist font
  subsets: ["latin"],  // Specifies which character subsets to load (e.g., "latin" characters)
});

// The Geist_Mono font configuration for a monospace font.
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",  // A custom CSS variable for the Geist Mono font
  subsets: ["latin"],  // Specifies the character subsets (e.g., "latin" characters)
});

// This provides the meta data in the HTML <head> tag, such as title and description (favicons, SEO)

export const metadata: Metadata = {
  title: "Next App",  // The title of the website shown in the browser tab
  description: "Generated by create next app",  // A short description for the page (can be used for SEO)
};

// Typing the 'children' prop as ReactNode, allowing any valid JSX content
export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en"> {/* Sets the language of the page to English */}
      <body className={`${geistSans.variable} ${geistMono.variable} bg-black text-white antialiased`}>
        {children} {/* Renders any child components inside the body of the HTML */}
      </body>
    </html>
  );
}
